global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'skeleton-app'

scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'skeleton'
    scrape_interval: 5s
    static_configs:
      - targets: ['app:8081']

  - job_name: 'mysqld_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'mysqld_exporter:9104' ]

  - job_name: 'pushgateway'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: [ 'pushgateway:9091' ]

  remote_write:
    - url: http://cortex:9009/api/prom/push
      queue_config:
        capacity: 5000
        max_shards: 20
        min_shards: 5
        max_samples_per_send: 1000